### ISSUE TITLE
Ionic 1 app crashes on open. Works well after removing the plugin

### ISSUE THREAD

**Issue by KPkun** [OneSignal/OneSignal-Cordova-SDK#438]
### Description:
App crashes only in the case where the plugin is installed.
Once removed, the app works fine.
I tried removing a few plugins to check compatibility but nothing works.
I also checked the common issues guidelines and I am not using any incompatible plugins.
I tried upgrading android to 7.1.0 and 7.1.1 but build fails with other errors. I could only elimate all reasons except the plugin in case of android@6.3.0

### Environment
**Pugin list:**
```
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-badge 0.8.1 "Badges"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-clipboard-x 1.0.1 "Clipboard"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-mixpanel 4.2.0 "Mixpanel"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
phonegap-plugin-push 1.3.0 "PushPlugin"
```

**Ionic info:**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0) 

local packages:

    Cordova Platforms : android 6.3.0
    Ionic Framework   : ionic1 1.3.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v8.9.2
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/krishna/Library/Android/SDK

Misc:

    backend : pro
```

**Steps taken:**
  Example:

  1. Add the onesignal-cordova-plugin to your project
  2. Cordova run android

**Crash type:**
App crashes immideately after trying to open. No white space. Takes micro seconds.
I see a grey window trying to fill in the phone screen but closes before the app opens.

**Comment by jkasten2** [comment]
@KPkun Can you check the logcat for a stacktrace? You can follow this guide on getting this.
https://documentation.onesignal.com/docs/troubleshooting-android#section-how-to-get-a-crash-or-error-log-from-an-android-device

Also can you share the build log when you try to update to cordova-android@7.x?

**Comment by KPkun** [comment]
@jkasten2 I'll do that.
Meanwhile, can you confirm if the plugin needs android 7+
If it doesn't work with android@6.3.0 there is no point.
For my project setup, I prefer having android@6.3.0 as of now.

**Comment by jkasten2** [comment]
@KPkun android@7.0.0 or newer isn't required for the OneSignal SDK to work. However there are a number of Android plugin conflict issues that are resolved when using this version. The conflicts may times don't show until run time which the logcat should provide a class not found error if this is the case.

**Comment by KPkun** [comment]
logcat after opening the app.
I selected log level as error
Does this say anything? @jkasten2 
```
10-11 16:50:52.734 22632-22632/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.companyname.productname, PID: 22632
                                                   java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
                                                       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:6257)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5775)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5693)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6577)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/data/app/com.companyname.productname-2/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.productname-2/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:6257) 
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5775) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5693) 
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                       at android.os.Looper.loop(Looper.java:156) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6577) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831) 
10-11 16:50:52.741 505-785/? E/logserver: imonitor_add_dynamic_path, path:/data/system/dropbox/data_app_crash@1539244252738.txt
10-11 16:50:52.746 1160-4852/? E/ReportTools: This is not beta user build
```

**Comment by KPkun** [comment]
Works with plugin version 2.3.3

**Comment by jkasten2** [comment]
@KPkun Thanks for the logcat, this does look like an issue of mismatched versions of Firebase and the Google Play services between the plugins in your app. Updating to `android@7.0.0` should fix this issue as OneSignal can correctly align the versions of these libraries to fix the issue when building.

Is there a specific issue that is preventing you from upgrading Cordova to `android@7.0.0`?

**Comment by Gercekefsane** [comment]
Same problem android 7.1.1

**Comment by jkasten2** [comment]
@Gercekefsane Can you provide a full stacktrace as well as a list of plugins and versions like @KPkun as listed above?

Please also provide your `config.xml` so we can double check this too.

**Comment by Nightsd01** [comment]
Closing due to no response - please feel free to reply and provide a full stacktrace + `config.xml` if you are still having this issue and we'll be happy to reopen and help investigate.
