### ISSUE TITLE
cannot find symbol   private static OSEmailSubscriptionObserver emailSubscriptionObserver;

### ISSUE THREAD

**Issue by ngangchill** [OneSignal/OneSignal-Cordova-SDK#325]
i'm having some problem with this sdk.
Error screen :
![onesignal](https://user-images.githubusercontent.com/4242225/36892050-c7a45806-1e2d-11e8-8294-9510962db2ab.PNG)

i can't get what is happening.Need helps

**Comment by ngangchill** [comment]
works fine with onesignal-cordova-plugin 2.2.2 but went wrong with onesignal-cordova-plugin 2.3.1.

**Comment by Nightsd01** [comment]
@ngangchill are you certain you are using 2.3.1? This was a known issue with 2.3.0 but should have been resolved in 2.3.1

**Comment by ngangchill** [comment]
thnx...
i have reinstalled the plugin && works  fine now @Nightsd01
