### ISSUE TITLE
[2.10.0] Error for existing project | JSONException; must be caught or declared to be thrown

### ISSUE THREAD

**Issue by indraraj26** [OneSignal/OneSignal-Cordova-SDK#645]
**Description:**
Same project is working fine with 2.8.4 version

Getting this error with 2.10.0
```
D:\app\platforms\android\app\src\main\java\com\plugin\gcm\OneSignalOutcomeController.java:25: error: unreported exception JSONException; must be caught or declared to be thrown
            CallbackHelper.callbackSuccess(jsSendUniqueOutcomeCallback, outcomeEvent.toJSONObject());
                                                                                                 ^
D:\app\platforms\android\app\src\main\java\com\plugin\gcm\OneSignalOutcomeController.java:45: error: unreported exception JSONException; must be caught or declared to be thrown
            CallbackHelper.callbackSuccess(jsSendOutcomeCallback, outcomeEvent.toJSONObject());
                                                                                           ^
D:\app\platforms\android\app\src\main\java\com\plugin\gcm\OneSignalOutcomeController.java:66: error: unreported exception JSONException; must be caught or declared to be thrown
            CallbackHelper.callbackSuccess(jsSendOutcomeWithValueCallback, outcomeEvent.toJSONObject());
```

**Environment**

```
ionic info

Ionic:

   Ionic CLI          : 6.6.0 (C:\Users\HP\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, (and 26 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\HP\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.10.2
   OS                : Windows 10

```

**Steps to Reproduce Issue:**

1.  add latest version of one signal
2. ionic cordova platform add android@8.1.0 && ionic cordova build android --prod

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by patrickbussmann** [comment]
Duplicate of #644

**Comment by mikechoch** [comment]
Duplicate of #644
